#!/bin/bash

echo "Sending JS to closure-compiler.appspot.com"
curl \
	--data-urlencode js_code@js/jquery.formwin.js \
	--data output_info=compiled_code \
	--data output_format=text \
	--data compilation_level=SIMPLE_OPTIMIZATIONS \
	http://closure-compiler.appspot.com/compile > js/jquery.formwin.min.js
