#!/bin/bash

echo "... generating formwin/js/jquery.formwin.min.js from formwin/js/jquery.formwin.js on closure-compiler.appspot.com"
curl \
	--data-urlencode js_code@formwin/js/jquery.formwin.js \
	--data output_info=compiled_code \
	--data output_format=text \
	--data compilation_level=SIMPLE_OPTIMIZATIONS \
	http://closure-compiler.appspot.com/compile > formwin/js/jquery.formwin.min.js
